# @package dataset
defaults:
  - /dataset/_base@_here_

name: beir_base
type: beir
# Hyukkyu/beir-* has things in train split, but it's actually test split.
split: train
corpus_split: train

beir_dataset: null

hf_name: Hyukkyu/beir-${dataset.beir_dataset}-qrels

# Column names for query/corpus datasets.
query_id_column: _id
query_text_column: text
corpus_id_column: _id
corpus_text_column: text
corpus_title_column: title
