# @package dataset
defaults:
  - /dataset/_base@_here_

name: beir_base
type: beir
split: test
corpus_split: train

beir_dataset: null

hf_name: BeIR/${dataset.beir_dataset}

# Column names for query/corpus datasets.
query_id_column: _id
query_text_column: text
corpus_id_column: _id
corpus_text_column: text
corpus_title_column: title
