services:
    SPLADE:
        image: hyukkyukang/splade:latest
        container_name: SPLADE

        shm_size: 24gb
        ulimits:
            memlock: -1
        stdin_open: true
        tty: true
        user: user
        network_mode: "host"

        environment:
            - TZ=Asia/Seoul
            - UID=${UID}
            - GID=${GID}

        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /home/hkkang/SPLADE:/home/user/SPLADE
        working_dir: /home/user/SPLADE
        command: |
            bash -c '
              set -e
              echo "export PATH=/home/user/.local/bin:$PATH" >> /home/user/.bashrc
              # Not sure why, but below two lines are necessary to correctly change
              # the owner of /home/user/ and folders in there
              echo "user" | sudo -S chmod 777 /home/user/
              echo "user" | sudo -S chmod 777 /home/user/.*
              # echo "user" | sudo -S chmod 777 /home/user/.cache
              # echo "user" | sudo -S chmod 777 /home/user/.local
              echo "user" | sudo -S chmod 777 /tmp/
              echo "user" | sudo -S groupmod -g ${GID} user
              echo "user" | sudo -S usermod -u ${UID} -g ${GID} user
              tail -f /dev/null
            '
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
