# @package testing
name: default

batch_size: 32
per_device_batch_size: null
num_workers: 4

precision: 16-mixed
use_cpu: false
strategy: ddp
num_devices: null
device_id: 0

k_list: [1, 5, 10, 50, 100]
save_run: false
run_path: null
checkpoint_path: null
