# @package dataset
name: base
type: custom

split: train

max_query_length: 32
max_doc_length: 256
num_negatives: 1
num_positives: 1

beir_dataset: null

use_hf: true
hf_name: null
hf_subset: null
hf_split: train
hf_cache_dir: null
hf_max_samples: null
hf_text_name: null
hf_teacher_name: null
hf_teacher_subset: null
hf_teacher_split: train
hf_teacher_cache_dir: null
hf_teacher_max_samples: null
hf_streaming: false
hf_shuffle_buffer_size: 10000
