# @package dataset
name: base
type: custom

split: train
corpus_split: ${.split}
hf_split: ${.split}

max_query_length: 256
max_doc_length: 256
max_padding: true
num_negatives: 1
num_positives: 1

beir_dataset: null

hf_name: null
hf_subset: null
hf_cache_dir: null
hf_max_samples: null
hf_skip_samples: 0
hf_data_files: null
query_corpus_hf_name: null
query_corpus_hf_cache_dir: null
query_corpus_hf_data_files: null
local_triplets_dir: null
