# @package dataset
defaults:
  - _base@_here_

name: msmarco_hf_train
type: msmarco
split: train

use_hf: true
hf_name: sentence-transformers/msmarco
hf_subset: triplets
hf_split: train
hf_text_name: null
hf_cache_dir: null
hf_max_samples: null
hf_skip_samples: ${training.val_sample_size}
hf_streaming: false
hf_shuffle_buffer_size: 10000
hf_teacher_name: sentence-transformers/msmarco-scores-ms-marco-MiniLM-L6-v2
hf_teacher_subset: pair
hf_teacher_split: train
hf_teacher_cache_dir: null
hf_teacher_max_samples: null

max_query_length: 256
max_doc_length: 256
num_negatives: 1
num_positives: 1
