# @package dataset
defaults:
  - _base@_here_

name: msmarco_spladev1_hardneg_minilm12
type: msmarco
split: train

use_hf: true
hf_name: json
hf_subset: null
hf_split: train
hf_text_name: sentence-transformers/msmarco
hf_cache_dir: null
hf_data_files:
  train: ${oc.env:SPLADE_HARDNEG_JSONL_PATH,null}
hf_max_samples: null
hf_streaming: true
hf_shuffle_buffer_size: 10000

max_query_length: 256
max_doc_length: 256
num_negatives: 1
num_positives: 1
