# @package dataset
defaults:
  - _base

name: msmarco_hf_val
type: msmarco
split: train

use_hf: true
hf_name: sentence-transformers/msmarco
hf_subset: triplets
hf_split: train
hf_max_samples: 20000

max_query_length: 32
max_doc_length: 256
num_negatives: 1
num_positives: 1
