# @package dataset
defaults:
  - _base@_here_

name: msmarco_hf_val
type: msmarco
split: train

use_hf: true
hf_name: sentence-transformers/msmarco
hf_subset: triplets
hf_split: train
hf_max_samples: 1000
hf_text_name: null
hf_cache_dir: null
hf_streaming: false
hf_shuffle_buffer_size: 10000
hf_teacher_name: null
hf_teacher_subset: null
hf_teacher_split: train
hf_teacher_cache_dir: null
hf_teacher_max_samples: null
use_integer_ids: true
integer_id_cache_dir: null

max_query_length: 256
max_doc_length: 256
num_negatives: 1
num_positives: 1
