# @package dataset
defaults:
  - _base

name: msmarco_test
type: msmarco
split: test

queries_path: ${dataset.data_dir}/msmarco/queries.test.jsonl
corpus_path: ${dataset.data_dir}/msmarco/corpus.jsonl
qrels_path: ${dataset.data_dir}/msmarco/qrels.test.tsv

max_query_length: 32
max_doc_length: 256
